## Problem 1. 
Consider the three mass-four spring system in figure below

<img src="springmass.png" width="500" height="300" /><br>

Determining the equations of motion from $\Sigma F_x=ma$, for each mass using its free-body diagram results in the following differential equations:

$$a_1+\frac{k_1+k_2}{m_1}x_1-\frac{k_2}{m_1}x_2=0$$

$$a_2-\frac{k_2}{m_2}x_1+\frac{k_2+k_3}{m_2}x_2-\frac{k_3}{m_2}x_3=0 \qquad (1)$$

$$a_3-\frac{k_3}{m_3}x_2+\frac{k_3+k_4}{m_3}x_3=0$$

where $k_1=k_4=10\,N/m, k_2=k_3=30\,N/m$ and $m_1=m_2=m_3=2\,kg$. Write the three equations in matrix form:

$$[k/m\,\text{matrix}][\text{displacement vector}\,x]=[\text{Acceleration vector}]$$

At a specific time where $a_1=0.1\,m/s^2, a_2=0.3\,m/s^2$ and $a_3=0.1\,m/s^2$, this forms a tridiagonal matrix. Solve for the acceleration of each mass using <b>your own implementation of the Thomas's algorithm</b> for solving the tridiagonal systems of equations.

#### 1.1
$$\begin{bmatrix}
-20 & 15 & 0 \\
15 & -30 & 15 \\
0 & 15 & -20 
\end{bmatrix}   \begin{bmatrix}
x_1 \\
x_2 \\
x_3 
\end{bmatrix}=\begin{bmatrix}
0.1 \\
0.3 \\
0.1 
\end{bmatrix}     $$

In [2]:
#1.2
import numpy as np
def thomas(f,g,e,b):
    
    for i in range(1,len(f),1):
        f[i]=f[i]-g[i-1]*(e[i]/f[i-1])
        b[i]=b[i]-b[i-1]*(e[i]/f[i-1])
        
    x=np.empty(b.shape)
    x[len(b)-1]=b[len(b)-1]/f[len(b)-1]
    for i in range(len(b)-2,-2,-1):
        x[i]=(b[i]-g[i]*x[i+1])/f[i]
    return x
    

In [3]:
#1.3
f=np.array([-20,-30,-20])
e=np.array([0,15,15])
g=np.array([15,15,0])
a=np.array([0.1,0.3,0.1])
print(f'{thomas(f,g,e,a)}')


[-0.05745536 -0.06994048 -0.05892857]


## Problem 2.
<b>a)</b> Implement the Cholesky factorization algorithm in python which is analogous to LU factorization but applicable only for symmetric matrices. Compute the Cholesky factrization for the matrix:

$$A=\begin{bmatrix}
2 & 1 & 1 \\
1 & 4 & 2 \\
1 & 2 & 6 
\end{bmatrix} \qquad (3)$$

<b>b)</b> The following system of equations is designed to determine concentrations (the c's in g/$\text m^3$) in a series of coupled reactors as a function of the amount of mass input to each reactor (the right-hand sides in g/day),

$$15c_1-3c_2-c_3=3300 \qquad$$
$$-3c_1+18c_2-6c_3=1200 \qquad (4)$$
$$-4c_1-1c_2+12c_3=2400 \qquad $$

Solve this problem with the Gauss-seidel iteration method to $\epsilon_S=5$%.</p>
<b>Note:</b>This problem was given on the labaratory 8. 

In [15]:
#2.1
def cholesky(A):
    L=np.zeros(A.shape)
    LT=np.zeros(A.shape)
    for R in range (0,len(A),1):
        for C in range(0,R+1,1):
            sum=0
            if (R==C):
                for i in range(0,C,1):
                    sum=sum+L[C,i]**2
                L[C,C]=(A[C,C]-sum)**0.5
            else:
                for i in range(0,C,1):
                    sum=sum+L[R,i]*L[C,i]
                L[R,C]=(A[R,C]-sum)/L[C,C]
    for C in range(0,len(A),1):
        for R in range(0,len(A),1):
            LT[C,R]=L[R,C]
    return L,LT

In [16]:
AB=np.array([[4,12,-16],[12,37,-43],[-16,-43,98]])
print(f'{cholesky(AB)}')


(array([[ 2.,  0.,  0.],
       [ 6.,  1.,  0.],
       [-8.,  5.,  3.]]), array([[ 2.,  6., -8.],
       [ 0.,  1.,  5.],
       [ 0.,  0.,  3.]]))


In [18]:
#2.3
import numpy as np
def gaussseidel(A,b,E):
    x=np.zeros(len(b))
    xold=np.zeros(len(b))
    error=100
    err=np.zeros(len(b))
    while error>E:
        for R in range(0,len(A),1):
            sum=0
            for C in range(0,len(A),1):
                sum=sum+x[C]*A[R,C]
            x[R]=(b[R]-sum+x[R]*A[R,R])/A[R,R]
        for i in range(0,len(b),1):
            err[i]=abs((x[i]-xold[i])/x[i])*100
        error=np.max(err)
        xold=np.copy(x)  
    
    return x

In [19]:
#2.4
A=np.array([[15,-3,-1],[-3,18,-6],[-4,-1,12]])
b=np.array([3300,1200,2400])
print(f'{gaussseidel(A,b,5)}')

[283.70282304 217.80331743 312.71788413]
