In [1]:
import numpy as np
def gaussseidel(A,b,E):
    x=np.empty(b.shape)
    yold=np.empty(b.shape)
    ynew=np.empty(b.shape)
    err=np.empty(b.shape)
    
    for i in range(0,5,1):
        for R in range(0,len(A),1):
            old=x[0]
            sum=0
            for C in range(0,len(A),1):
                sum=sum+x[C]*A[R,C]
            x[R]=(b[R]-sum+x[R]*A[R,R])/A[R,R]
            ynew=x
        print(ynew)
        for i in range(0,len(b),1):
            err[i]=abs((ynew[i]-yold[i])/ynew[i])*100
        error=max(err)
        print(yold)
        yold=ynew       
        

    return x
            
            
            
A=np.array([[3,-0.1,-0.2],[0.1,7,-0.3],[0.3,-0.2,10]])
d=np.array([7.85,-19.3,71.4])
print(f'{gaussseidel(A,d,0.01)}')
            
            

[ 2.61666667 -2.79452381  7.00560952]
[6.95313643e-310 2.67761181e-312 4.94065646e-324]
[ 2.99055651 -2.49962468  7.00029081]
[ 2.99055651 -2.49962468  7.00029081]
[ 3.0000319  -2.49998799  6.99999928]
[ 3.0000319  -2.49998799  6.99999928]
[ 3.00000035 -2.50000004  6.99999999]
[ 3.00000035 -2.50000004  6.99999999]
[ 3.  -2.5  7. ]
[ 3.  -2.5  7. ]
[ 3.  -2.5  7. ]


In [ ]:
print('mamam')