In [4]:
def gauss(A,b):
    
    for C in range (0,len(b)-1,1):
        for R in range (C+1,len(b),1):
            m=A[R,C]/A[C,C]
            A[R,:]=A[R,:]-m*A[C,:]
            b[R]=b[R]-m*b[C]
            
    x=np.empty(b.shape)
    x[len(b)-1]=b[len(b)-1]/A[len(b)-1,len(b)-1]
    for R in range(len(b)-2,-1,-1):
        sum=0
        for C in range(R+1,len(b),1):
            sum=sum+x[C]*A[R,C]
        
        x[R]=(b[R]-sum)/A[R,R]
    return A,x

import numpy as np
from scipy import linalg

A=np.array([[1,-2,1],[2,-1,2],[3,-1,2]])
b=np.array([8,10,11])
print(f'{gauss(A,b)}')
            

(array([[ 1, -2,  1],
       [ 0,  3,  0],
       [ 0,  0, -1]]), array([ 1., -2.,  3.]))


In [3]:
def LU(A,b):
    m=np.empty(A.shape)
    U=np.copy(A)
    for C in range (0,len(b)-1,1):
        for R in range (C+1,len(b),1):
            m[R,C]=U[R,C]/U[C,C]
            U[R,:]=U[R,:]-m[R,C]*U[C,:]
            
       
    L=np.empty(A.shape)
    for C in range (0,len(b),1):
        for R in range(0,len(b),1):
            if(R==C):
                L[R,C]=1
            elif(C>R):
                L[R,C]=0
            else:
                L[R,C]=m[R,C]
    y=np.empty(b.shape)
    y[0]=b[0]
    for R in range(1,len(b),1):
        sum=0
        for C in range(0,R,1):
            sum=sum+y[C]*L[R,C]
        y[R]=b[R]-sum
        
    x=np.empty(y.shape)
    x[len(y)-1]=y[len(y)-1]/U[len(y)-1,len(y)-1]
    for R in range(len(y)-2,-1,-1):
        sum=0
        for C in range(R+1,len(y),1):
            sum=sum+x[C]*U[R,C]
        
        x[R]=(y[R]-sum)/U[R,R]
        
    return L,U,x 

In [16]:
A=np.array([[4,3],[2,5]])
A1=np.array([[1,3/4],[2,5]])
c=np.array([8,14])
c1=np.array([2,14])
print(f'{LU(A1,c1)}')
x=np.linalg.solve(A,c)
print(f'{x}')

(array([[1., 0.],
       [2., 1.]]), array([[1.  , 0.75],
       [0.  , 3.5 ]]), array([-0.14285714,  2.85714286]))
[-0.14285714  2.85714286]


In [52]:
A=np.array([[6,-2,2],[12,-8,6],[3,-13,2]])
b=np.array([8,14,-17])
np.linalg.solve(A,b)


array([1., 2., 3.])

In [1]:
def inverse(A):
    m=np.empty(A.shape)
    U=np.copy(A)
    B=np.empty(A.shape)
    for R in range(0,len(A),1):
        for C in range(0, len(A),1):
            if(R==C):
                B[R,C]=1
            else:
                B[R,C]=0
           
    for C in range (0,len(A)-1,1):
        for R in range (C+1,len(A),1):
            m[R,C]=U[R,C]/U[C,C]
            U[R,:]=U[R,:]-m[R,C]*U[C,:]
            
    L=np.empty(A.shape)
    for C in range (0,len(A),1):
        for R in range(0,len(A),1):
            if(R==C):
                L[R,C]=1
            elif(C>R):
                L[R,C]=0
            else:
                L[R,C]=m[R,C]
                
    y=np.empty(len(B))
    x=np.empty(y.shape)
    inv=np.empty(A.shape)
    
    for C in range(0,len(B),1):
        for R in range(0,len(B),1):
            y[0]=B[0,R]
            for R1 in range(1,len(B),1):
                sum=0
                for C1 in range(0,R1,1):
                    sum=sum+y[C1]*L[R1,C1]
        
                y[R1]=B[R1,R1]-sum
                print(f'{y}')
   
            x[len(y)-1]=y[len(y)-1]/U[len(y)-1,len(y)-1]
            for R2 in range(len(y)-2,-1,-1):
                sum=0
                for C2 in range(R2+1,len(y),1):
                    sum=sum+x[C2]*U[R2,C2]
        
                x[R2]=(y[R2]-sum)/U[R2,R2]
                inv[]
                print(f'{x}')
    
           
                
    return inv

In [5]:
B=np.array([[1,3],[2,5]])
inverse(B)

[ 1. -1.]
[-2.  1.]
[0. 1.]
[ 3. -1.]
[ 1. -1.]
[-2.  1.]
[0. 1.]
[ 3. -1.]


array([[9.35219335e-313, 6.95312939e-310],
       [4.94065646e-324,             nan]])