In [10]:
import numpy as np
def jacobi(A,b):
    x_new=np.empty(b.shape)
    x_old=np.empty(b.shape)
    for i in range(0,len(b),1):
        x_old[i]=0
    for i in range(0,5,1):
        for R in range(0,len(b),1):
            
            sum=0
            for C in range(0,len(b),1):
                sum=sum+x_old[C]*A[R,C]
            x_new[R]=(b[R]-sum+x_old[R]*A[R,R])/A[R,R]
        x_old=x_new
    return x_new

A=np.array([[3,-0.1,-0.2],[0.1,7,-0.3],[0.3,-0.2,10]])
d=np.array([7.85,-19.3,71.4])
print(f'{jacobi(A,d)}')

[ 2.99999999 -2.5         7.        ]


In [6]:
import numpy as np
def gaussseidel(A,b,E):
    x=np.empty(b.shape)
    old=0
    err=100
    for i in range (0,len(b),1):
        x[i]=0
    for i in range(0,5,1):
        for R in range(0,len(A),1):
            old=x[0]
            sum=0
            for C in range(0,len(A),1):
                sum=sum+x[C]*A[R,C]
            x[R]=(b[R]-sum+x[R]*A[R,R])/A[R,R]
        print(f'{x}')
               
             
    return x
            
            
            
A=np.array([[3,-0.1,-0.2],[0.1,7,-0.3],[0.3,-0.2,10]])
d=np.array([7.85,-19.3,71.4])
print(f'{gaussseidel(A,d,0.01)}')

[ 2.61666667 -2.79452381  7.00560952]
[ 2.99055651 -2.49962468  7.00029081]
[ 3.0000319  -2.49998799  6.99999928]
[ 3.00000035 -2.50000004  6.99999999]
[ 3.  -2.5  7. ]
[ 3.  -2.5  7. ]
