In [94]:
import numpy as np

def f(x):
    return 2*np.sin(x)-x**2/10

def gold(x_l,x_u,tol):
    d=(np.sqrt(5)-1)*(x_u-x_l)/2
    d0=x_u-x_l
    imax=np.ceil(np.log(tol/d0)/np.log((np.sqrt(5)-1)/2))
    x1=x_l+d
    x2=x_u-d
    f1=f(x1)
    f2=f(x2)
    for i in range(1,17,1):
        d=(np.sqrt(5)-1)*(x_u-x_l)/2
        if (f1>f2):
            x_l=x2
            x2=x1
            x1=x_l+d
            f2=f1
            f1=f(x1)
        else:
            x_u=x1
            x1=x2
            x2=x_u-d
            f1=f2
            f2=f(x2)
    if f1>f2:
        return x1,f1
    else:
        return x2,f2
        
                   

In [95]:
xopt,fxopt=gold(1,4,0.001)
print(f'{xopt,fxopt}')

(1.437694101250947, 1.7756135045562806)


In [26]:
import numpy as np
def f(x):
    return 2*np.sin(x)-x**2/10
def parabolic(x0,x1,x2,n):
    f0=f(x0)
    f1=f(x1)
    f2=f(x2)
    for i in range(1,n+1,1):
        
        x3=(f0*(x1**2-x2**2)+f1*(x2**2-x0**2)+f2*(x0**2-x1**2))/(2*f0*(x1-x2)+2*f1*(x2-x0)+2*f2*(x0-x1))
        f3=f(x3)
        if(f3>f1 and x3>x1):
            x0=x1
            x1=x3
            f0=f1
            f1=f3
        elif(f3>f1 and x3<x1):
            x2=x1
            x1=x3
            f2=f1
            f1=f3
        elif(f3<f1 and x3>x1):
            x2=x3
            f2=f3
        else:
            x0=x3
            f0=f3
    if f3>f1:   
        return x3,f3
    else:
        return x1,f1

In [27]:
print(f'{parabolic(0,1,4,5)}')

(1.4275483108893277, 1.7757256531343095)


In [47]:
import numpy as np
def fd1(x):
    return 2*np.cos(x)-x/5
def fd2(x):
    return -2*np.sin(x)-1/5
def newton(x0,E):
    err=100
    xold=x0
    while err>E:
        xnew=xold-fd1(xold)/fd2(xold)
        err=abs((xnew-xold)/xnew)*100
        xold=xnew
        print(f'{xnew}')
    return xnew
        

In [48]:
print(f'{newton(2.5,0.01)}')

0.9950815513259932
1.4690107527596457
1.4276423210187772
1.4275517793013137
1.4275517793013137


In [ ]:
def dfdx(x,y):
    return 2*y+2-2*x
def dfdy(x,y):
    return 2*x-4*y
def g(h):
    return -180*h**2+72*h-7
def steepest(h,x0,y0):
    x=x0+dfdx(x0,y0)*h
    y=y0+dfdy(x0,y0)*h
    

In [84]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
